-- All Negative Comments from September 2024

-- Use this query for getting all comments
WITH BASE_VOC AS (
SELECT b.unit_name, b.ext_ref,a.PARTICIPATES_IN_LETS_TALK_FLIK, a.scott_davis_direct_reports
FROM FLIK_ANALYTICS.DIM.GOLDLIST a
RIGHT JOIN FLIK_INTERMEDIATE.FIVETRAN.INT_FLIK_FIVETRAN__GOLDLIST_ACTIVE_UNITS b
ON a.extref = b.ext_ref
WHERE lower(a.PARTICIPATES_IN_LETS_TALK_FLIK) NOT IN ('no', 'test')
AND b.ext_ref NOT IN ('1', '4440', '33940', '5')

-- Count of Monthly VOC Responses by SDDR/UNIT_SAP_NUMBER
), VOC_UNIT_RESPONSES AS (
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YEAR(AUDIT_DATE) AS YR, MONTH(AUDIT_DATE) AS MO, COUNT(DISTINCT RESPONSE_ID) AS RESPONSE_COUNT
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED
WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' OR UNIT_BUSINESS_PORTFOLIO is null)  -- removes test B&I account & Insights test accounts
AND DATATYPE = 'Responses' -- only responses
AND SURVEY_NAME ILIKE '%voc%' -- only VOC surveys
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- removes test B&I account & Insights test accounts
AND RESPONSE_VALID = 'Yes' -- only valid responses
AND ISGOLDLISTACTIVE = TRUE -- only active units
AND UNIT_SAP_NUMBER IN (SELECT ext_ref FROM BASE_VOC) -- only units that participated in LETS TALK FLIK
AND HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS IS NOT NULL -- only responses with a SDDR
GROUP BY SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YR, MO
ORDER BY YR DESC, MO DESC, SCOTT_DAVIS_DIRECT_REPORTS

)
SELECT b.SCOTT_DAVIS_DIRECT_REPORTS,a.UNIT_SAP_NUMBER, b.UNIT_NAME, a.FULL_RECORDED_DATE, a.QUESTION_TEXT, a.QUESTION_RESPONSE, ROUND(AVG(a.SENTIMENT), 2) AS AVG_SENTIMENT, 
CASE WHEN AVG_SENTIMENT <= 2.33 AND AVG_SENTIMENT >= 1 THEN 'Negative'
WHEN AVG_SENTIMENT > 2.33 AND AVG_SENTIMENT < 3.67 THEN 'Neutral'
WHEN AVG_SENTIMENT <= 5 AND AVG_SENTIMENT >= 3.67 THEN 'Positive' 
END AS SENTIMENT_LABEL
FROM FLIK_INTERMEDIATE.DATA_SCIENCE.FLIK_DATA_SCIENCE__FLIK_VOC_COMMENTS_CATEGORIES a
LEFT JOIN BASE_VOC b
ON a.UNIT_SAP_NUMBER = b.EXT_REF
WHERE a.RESPONSE_ID IN (SELECT DISTINCT RESPONSE_ID FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED WHERE RESPONSE_VALID = 'Yes' AND ISGOLDLISTACTIVE = TRUE)
AND SCOTT_DAVIS_DIRECT_REPORTS = 'Peter Soguero'
AND a.FULL_RECORDED_DATE BETWEEN DATEADD('month', -1, DATE_TRUNC('month', CURRENT_DATE()))
    AND LAST_DAY(DATEADD('month', -1, CURRENT_DATE()))
AND b.SCOTT_DAVIS_DIRECT_REPORTS IS NOT NULL 
AND b.SCOTT_DAVIS_DIRECT_REPORTS <> ''
GROUP BY  a.RESPONSE_ID, a.QUESTION_TEXT, a.QUESTION_RESPONSE,  a.UNIT_SAP_NUMBER, b.UNIT_NAME, b.SCOTT_DAVIS_DIRECT_REPORTS, a.FULL_RECORDED_DATE
HAVING AVG_SENTIMENT <= 2.33 AND AVG_SENTIMENT >= 1
ORDER BY b.SCOTT_DAVIS_DIRECT_REPORTS, a.FULL_RECORDED_DATE DESC
;

