-- Table of open tickets from QA audits
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, UNIT_NAME, YEAR(TICKET_CREATION_DATE_EST) AS YR, MONTH(TICKET_CREATION_DATE_EST) AS MO, DAY(TICKET_CREATION_DATE_EST) AS DAY,
TICKET_ID, TICKET_ROOT_CAUSE, TICKET_CRITICAL, TICKET_DETAILS
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED 
WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' or UNIT_BUSINESS_PORTFOLIO is null)  -- excludes 'test' portfolios but includes 'null' portfolios
AND SCOTT_DAVIS_DIRECT_REPORTS = 'Brian Donohue'
AND SURVEY_ID = 'SV_cBggdZ7uWwWjmgl' -- include only QA survey
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- removes test B&I account & Insights test accounts
AND RESPONSE_VALID = 'Yes' -- only valid responses
AND DATATYPE = 'Tickets' -- only tickets
AND TICKET_STATUS = 'Open' -- only open tickets
AND ISGOLDLISTACTIVE = TRUE -- only active accounts
AND SCOTT_DAVIS_DIRECT_REPORTS IS NOT NULL -- only non-null SDDR
AND SCOTT_DAVIS_DIRECT_REPORTS <> '' -- only non-blank SDDR
AND YR = YEAR(DATEADD('month', -1, CURRENT_DATE())) AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE())) -- Only September 2024
ORDER BY SCOTT_DAVIS_DIRECT_REPORTS, YR DESC, MO DESC, DAY DESC
;
