-- Table of failed QA audits
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, UNIT_NAME, YEAR(AUDIT_DATE) AS YR, MONTH(AUDIT_DATE) AS MO, DAY(AUDIT_DATE) AS DAY, ROUND(AVG(CATEGORY_SCORE),2) AS QA_SCORE,
 CASE WHEN QA_SCORE < 90 THEN 'FAIL'
 ELSE 'PASS'
 END AS "PASS/FAIL"
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED
WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' or UNIT_BUSINESS_PORTFOLIO is null)  -- Excludes 'test' portfolios but includes 'null' portfolios
AND SCOTT_DAVIS_DIRECT_REPORTS = 'Brian Donohue'
AND SURVEY_ID = 'SV_cBggdZ7uWwWjmgl' -- Include only QA survey
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- Removes test accounts
AND RESPONSE_VALID = 'Yes' -- Only valid responses
AND ISGOLDLISTACTIVE = TRUE -- Only active accounts
AND CATEGORY = 'Total Score' AND CATEGORY_SCORE_ID = 'PercentScore' -- Only total score
AND YR = YEAR(DATEADD('month', -1, CURRENT_DATE())) AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE())) -- Only September 2024
GROUP BY RESPONSE_ID, UNIT_NAME, UNIT_SAP_NUMBER, UNIT_INDUSTRY, SCOTT_DAVIS_DIRECT_REPORTS, YR, MO, DAY
HAVING QA_SCORE < 90 -- Only failed audits
ORDER BY SCOTT_DAVIS_DIRECT_REPORTS, YR DESC, MO DESC, DAY DESC
;