-- Monthly Infographic VOC Hyperlinks

-- Description: This script is used to get the VOC data for the hyperlinks in the VOC dashboard


--------------------------------------
-- Get list of active VOC units that participated in LETS TALK FLIK and get response count & avg CSAT scores for September 2024

WITH BASE_VOC AS (
SELECT b.unit_name, b.ext_ref,a.PARTICIPATES_IN_LETS_TALK_FLIK, a.scott_davis_direct_reports
FROM FLIK_ANALYTICS.DIM.GOLDLIST a
RIGHT JOIN FLIK_INTERMEDIATE.FIVETRAN.INT_FLIK_FIVETRAN__GOLDLIST_ACTIVE_UNITS b
ON a.extref = b.ext_ref
WHERE lower(a.PARTICIPATES_IN_LETS_TALK_FLIK) NOT IN ('no', 'test')
AND b.ext_ref NOT IN ('1', '4440', '33940', '5')

-- Count of Monthly VOC Responses by SDDR/UNIT_SAP_NUMBER
), VOC_UNIT_RESPONSES AS (
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YEAR(AUDIT_DATE) AS YR, MONTH(AUDIT_DATE) AS MO, COUNT(DISTINCT RESPONSE_ID) AS RESPONSE_COUNT
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED
WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' OR UNIT_BUSINESS_PORTFOLIO is null)  -- removes test B&I account & Insights test accounts
AND DATATYPE = 'Responses' -- only responses
AND SURVEY_NAME ILIKE '%voc%' -- only VOC surveys
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- removes test B&I account & Insights test accounts
AND RESPONSE_VALID = 'Yes' -- only valid responses
AND ISGOLDLISTACTIVE = TRUE -- only active units
AND UNIT_SAP_NUMBER IN (SELECT ext_ref FROM BASE_VOC) -- only units that participated in LETS TALK FLIK
AND HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS IS NOT NULL -- only responses with a SDDR
GROUP BY SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YR, MO
ORDER BY YR DESC, MO DESC, SCOTT_DAVIS_DIRECT_REPORTS
)

, UNIT_LIST AS (
    SELECT DISTINCT ext_ref AS UNIT_SAP_NUMBER, UNIT_NAME
    FROM BASE_VOC
)

, numbers1 AS (
SELECT 2019 as YR
UNION ALL
SELECT YR + 1
FROM numbers1
WHERE YR < YEAR(DATEADD('month', -1, CURRENT_DATE()))
)
, numbers2 AS (
SELECT 1 as MO
UNION ALL
SELECT MO + 1
FROM numbers2
WHERE MO < 12
)
, years_months AS (
SELECT YR, MO
FROM numbers1
CROSS JOIN numbers2
)


-- Use UNIT_LIST to get all the distinct UNIT_SAP_NUMBER that participated in LETS TALK FLIK
-- Use VOC_UNIT_RESPONSES to get the count of VOC responses by UNIT_SAP_NUMBER from each month & year
-- Use years_months to get all months from 2019 to 2024

-- Make sure years_months has a cross join with UNIT_LIST to get all the months for each UNIT_SAP_NUMBER
-- Then left join with VOC_UNIT_RESPONSES to get the count of VOC responses by UNIT_SAP_NUMBER from each month & year
-- Then use COALESCE to replace NULL values with 0

, CTE_HELPER1 AS (
SELECT *
FROM UNIT_LIST
CROSS JOIN years_months
)

, CTE_HELPER2 AS (
SELECT a.UNIT_NAME AS UNIT, a.UNIT_SAP_NUMBER, a.YR, a.MO, COALESCE(b.RESPONSE_COUNT, 0) AS RESPONSE_COUNT
FROM CTE_HELPER1 a
LEFT JOIN VOC_UNIT_RESPONSES b
ON a.UNIT_SAP_NUMBER = b.UNIT_SAP_NUMBER
AND a.YR = b.YR
AND a.MO = b.MO
ORDER BY a.UNIT_SAP_NUMBER, a.YR DESC, a.MO DESC
)
, CTE_UNIT_VOC_RESPONSES AS (
SELECT a.SCOTT_DAVIS_DIRECT_REPORTS, b.*
FROM BASE_VOC a
LEFT JOIN CTE_HELPER2 b
ON a.EXT_REF = b.UNIT_SAP_NUMBER
ORDER BY a.SCOTT_DAVIS_DIRECT_REPORTS, b.YR DESC, b.MO DESC, b.RESPONSE_COUNT DESC
), CTE_UNIT_VOC_RESPONSES_FILTERED AS (
SELECT *
FROM CTE_UNIT_VOC_RESPONSES
WHERE YR = YEAR(DATEADD('month', -1, CURRENT_DATE()))
AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE()))
ORDER BY SCOTT_DAVIS_DIRECT_REPORTS, YR DESC, MO DESC, RESPONSE_COUNT DESC
)

, CTE_CSAT AS (
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, RESPONSE_ID, AUDIT_DATE, SURVEY_NAME, SURVEY_ID, RESPONSE_VALID, UNIT_PARTICIPATES_IN_LTF, ISGOLDLISTACTIVE,
UNIT_NAME, UNIT_SAP_NUMBER, UNIT_INDUSTRY, QUESTION_QID_ROOT, QUESTION_TEXT, QUESTION_TYPE, 
CASE WHEN QUESTION_QID_ROOT IN ('QID190', 'QID292') THEN SUBSTR(QUESTION_RESPONSE, 1, 1)
ELSE QUESTION_RESPONSE
END AS CSAT
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED
WHERE QUESTION_TYPE NOT IN ('FileUpload', 'TE', 'DD', 'MC') -- Only CSAT questions
AND (UNIT_BUSINESS_PORTFOLIO <> 'Test' OR UNIT_BUSINESS_PORTFOLIO is null)  -- removes test B&I account & Insights test accounts
AND DATATYPE = 'Responses' -- only responses
AND SURVEY_NAME ILIKE '%voc%' -- only VOC surveys
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- removes test B&I account & Insights test accounts
AND RESPONSE_VALID = 'Yes' -- only valid responses
AND ISGOLDLISTACTIVE = TRUE -- only active units
AND HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS IS NOT NULL -- only responses with a SDDR
GROUP BY ALL
) 

, CTE_CSAT_BASE AS (
SELECT SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YEAR(AUDIT_DATE) AS YR, MONTH(AUDIT_DATE) AS MO, ROUND(AVG(CSAT),2) AS AVG_CSAT
FROM CTE_CSAT
WHERE YR = YEAR(DATEADD('month', -1, CURRENT_DATE()))
AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE()))
GROUP BY SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YR, MO
ORDER BY YR DESC, MO DESC, SCOTT_DAVIS_DIRECT_REPORTS
)

-- Join CTE_UNIT_VOC_RESPONSES_FILTERED with CTE_CSAT_BASE to get the average CSAT score for each UNIT_SAP_NUMBER
-- Then use COALESCE to replace NULL values with 0
SELECT a.*, COALESCE(b.AVG_CSAT, NULL) AS AVG_CSAT
FROM CTE_UNIT_VOC_RESPONSES_FILTERED a
LEFT JOIN CTE_CSAT_BASE b
ON a.UNIT_SAP_NUMBER = b.UNIT_SAP_NUMBER
WHERE a.SCOTT_DAVIS_DIRECT_REPORTS = 'Neil Gardner'
ORDER BY a.SCOTT_DAVIS_DIRECT_REPORTS, a.YR DESC, a.MO DESC, a.RESPONSE_COUNT DESC
;
