-- Table of open tickets from QA audits
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, UNIT_NAME, 
YEAR(TICKET_CREATION_DATE_EST) AS YR, MONTH(TICKET_CREATION_DATE_EST) AS MO, DAY(TICKET_CREATION_DATE_EST) AS DAY,
TICKET_ID, TICKET_ROOT_CAUSE, TICKET_CRITICAL, TICKET_DETAILS
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED 
WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' or UNIT_BUSINESS_PORTFOLIO is null)  
AND SCOTT_DAVIS_DIRECT_REPORTS = '{SDDR_NAME}' 
AND SURVEY_ID = 'SV_cBggdZ7uWwWjmgl'  
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') 
AND RESPONSE_VALID = 'Yes' 
AND DATATYPE = 'Tickets' 
AND TICKET_STATUS = 'Open' 
AND ISGOLDLISTACTIVE = TRUE 
AND SCOTT_DAVIS_DIRECT_REPORTS IS NOT NULL 
AND SCOTT_DAVIS_DIRECT_REPORTS <> '' 
AND YR = YEAR(DATEADD('month', -1, CURRENT_DATE())) AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE()))  
ORDER BY SCOTT_DAVIS_DIRECT_REPORTS, YR DESC, MO DESC, DAY DESC;
