-- Table of failed tickets from failed QA audits
WITH QA_BASE_FAIL_1 AS (
    SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_SAP_NUMBER, YEAR(AUDIT_DATE) AS YR, MONTH(AUDIT_DATE) AS MO,
    ROUND(AVG(CATEGORY_SCORE),2) AS SCORE,
    CASE WHEN SCORE < 90 THEN 'FAIL'
    ELSE 'PASS'
    END AS "PASS_FAIL"
    FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED
    WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' or UNIT_BUSINESS_PORTFOLIO is null)  -- Excludes 'test' portfolios but includes 'null' portfolios
    AND SCOTT_DAVIS_DIRECT_REPORTS = '{SDDR_NAME}'
    AND SURVEY_ID = 'SV_cBggdZ7uWwWjmgl' -- Include only QA survey
    AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- Removes test accounts
    AND RESPONSE_VALID = 'Yes' -- Only valid responses
    AND ISGOLDLISTACTIVE = TRUE -- Only active accounts
    AND CATEGORY = 'Total Score' AND CATEGORY_SCORE_ID = 'PercentScore' -- Only total score
    AND YR = YEAR(DATEADD('month', -1, CURRENT_DATE())) AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE())) -- Only September 2024
    GROUP BY RESPONSE_ID, UNIT_SAP_NUMBER, HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS, YR, MO
    ORDER BY HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS, YR DESC, MO DESC
)

, QA_BASE_TICKETS AS (
SELECT HIERARCHY_SCOTT_DAVIS_DIRECT_REPORTS AS SCOTT_DAVIS_DIRECT_REPORTS, UNIT_NAME, UNIT_SAP_NUMBER, YEAR(TICKET_CREATION_DATE_EST) AS YR, MONTH(TICKET_CREATION_DATE_EST) AS MO, DAY(TICKET_CREATION_DATE_EST) AS DAY,TICKET_ID, TICKET_ROOT_CAUSE, TICKET_CRITICAL, TICKET_DETAILS, TICKET_SOLUTION, TICKET_DAYS_TO_CLOSE
FROM FLIK_ANALYTICS.CURIOSITY.SURVEYS_COMBINED
WHERE (UNIT_BUSINESS_PORTFOLIO <> 'Test' or UNIT_BUSINESS_PORTFOLIO is null)  -- Excludes 'test' portfolios but includes 'null' portfolios
AND SURVEY_ID = 'SV_cBggdZ7uWwWjmgl' -- Include only QA survey
AND UNIT_SAP_NUMBER NOT IN ('1', '4440', '33940') -- Removes test accounts
AND RESPONSE_VALID = 'Yes' -- Only valid responses
AND ISGOLDLISTACTIVE = TRUE -- Only active accounts
AND DATATYPE = 'Tickets' -- Only tickets
AND TICKET_STATUS = 'Closed' -- Only closed tickets
AND YR = YEAR(DATEADD('month', -1, CURRENT_DATE())) AND MO = MONTH(DATEADD('month', -1, CURRENT_DATE())) -- Only September 2024
ORDER BY YR DESC, MO DESC, SCOTT_DAVIS_DIRECT_REPORTS
)
SELECT *
FROM QA_BASE_TICKETS
WHERE UNIT_SAP_NUMBER IN (SELECT UNIT_SAP_NUMBER FROM QA_BASE_FAIL_1 WHERE PASS_FAIL = 'FAIL')
ORDER BY SCOTT_DAVIS_DIRECT_REPORTS, YR DESC, MO DESC, DAY DESC
;
